#line ${linenum} "${filename}"
// *********************************************************
// 
// File autogenerated for the ${pkgname} package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __${uname}CONFIG_H__
#define __${uname}CONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>

namespace ${pkgname}
{
  class ${name}Config
  {
  private:
    class AbstractParameterDescription : public dynamic_reconfigure2::ParameterDescription
    {
    public:
      AbstractParameterDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method)
      {
        name_ = name;
        type_ = type;
        level_ = level;
        description_ = description;
        edit_method_ = edit_method;
      }
      
      virtual void clamp(${name}Config &config) = 0;
      virtual void level(int &level, ${name}Config &config1, ${name}Config &config2) = 0;
      void fromServer(ros::NodeHandle &nh, ${name}Config &config) = 0;
      void toServer(ros::NodeHandle &nh, const ${name}Config &config) = 0;
      bool fromMessage(dynamic_reconfigure2::ParameterSet &msg, ${name}Config &config) = 0;
      void toMessage(dynamic_reconfigure2::ParameterSet &msg, ${name}Config &config) = 0;
    };
    
    template <class T>
    class ParameterDescription : public AbstractParameterDescription
    {
    public:
      ParameterDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T ${name}Config::* field_) :
        AbstractParameterDescription(name, type, level, description, edit_method),
        field_(field)
      {}

      T ${name}Config::* field_;

      void clamp(${name}Config &config, const ${name}Config &max, const ${name}Config &min) const
      {
        if (config->*field_ > max->*field_)
          config->*field_ = max->*field_;
        
        if (config->*field_ < min->*field_)
          config->*field_ = min->*field_;
      }

      void level(int &level, const ${name}Config &config1, const ${name}Config &config2)
      {
        if (config1->*field_ != config2->*field_)
          *level |= level_;
      }

      void fromServer(ros::NodeHandle &nh, ${name}Config &config)
      {
        nh.getParam(name_, config->*field_);
      }

      void toServer(ros::NodeHandle &nh, const ${name}Config &config)
      {
        nh.setParam(name_, config->*field_);
      }

      bool fromMessage(dynamic_reconfigure2::ParameterSet &msg, ${name}Config &config)
      {
        return dynamic_reconfigure::ParameterSetTools::getParameter(name_, config_->*field);
      }

      void toMessage(dynamic_reconfigure2::ParameterSet &msg, ${name}Config &config)
      {
        return dynamic_reconfigure::ParameterSetTools::AppendParameter(name_, config_->*field);
      }
    };

    template <> // Max and min are ignored for strings.
    ParameterDescription<string>::clamp(${name}Config &config, const ${name}Config &max, const ${name}Config &min) const
    {
      return;
    }

    static int __num_parameters__ = ${num_parameters};
    AbstractParameterDescription<${name}Config> *parameters_[] = {
    };
    static ${name}Config __max__ = {
${maxes}
#line ${linenum} "${filename}"
    };
    static ${name}Config __min__ = {
${mins}
#line ${linenum} "${filename}"
    };
    static ${name}Config __default__ = {
${defaults}
#line ${linenum} "${filename}"
    };

$members
#line ${linenum} "${filename}"

    bool __fromMessage__(dynamic_reconfigure2::ParameterSet &msg)
    {
      int count = 0;
      for (int i = 0; i < __.num_parameters_; i++)
        if (__.parameters_[i]->getParameter(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ParameterSetTools::size(msg))
      // @todo Check that there are no duplicates.
    }

    void __toMessage__(dynamic_reconfigure2::ParameterSet &msg) const
    {
      for (int i = 0; i < __.num_parameters_; i++)
        __.parameters_[i]->appendParameter(msg, *this);
    }
    
    void __toServer__(const ros::NodeHandle &nh = ros::NodeHandle("~")) const
    {
      for (int i = 0; i < __.num_parameters_; i++)
        __.parameters_[i]->toServer(ros::NodeHandle nh);
    }

    void __fromServer__(const ros::NodeHandle &nh = ros::NodeHandle("~"))
    {
      for (int i = 0; i < __.num_parameters_; i++)
        __.parameters_[i]->fromServer(ros::NodeHandle nh);
    }

    static bool __getDescriptionMessage__(dynamic_reconfigure2::ConfigDescription &msg) 
    {
      msg.set_parameters_size(__num_parameters__);
      for (int i = 0; i < __.num_parameters_; i++)
        msg.parameters[i] = parameters_[i];
      msg.max = __max__;
      msg.min = __min__;
      msg.dflt = __default__;
    }

    void __clamp__()
    {
      for (int i = 0; i < __.num_parameters_; i++)
        __.parameters_[i]->clamp(*this, __.max_, __.min_)
    }

    uint32_t __level__(const ${name}Config &config) const
    {
      uint32_t level = 0;
      for (${name}Config.iterator i = config.parameters_.start(); i != config.parameters_.end(); i++)
        __.parameters_[i]->level(level, config, *this);
      return level;
    }
  };
}

#endif // __${uname}RECONFIGURATOR_H__
